# Generated by Django 5.0.3 on 2026-05-26 08:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('REVIEWER', 'Reviewer'), ('AUDITOR', 'Auditor')], default='ANALYST', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='esg_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='esg_user_permissions', to='auth.permission')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esg.tenant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('SAP', 'SAP ERP'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Travel System (Concur)')], max_length=50)),
                ('file_url', models.URLField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.ingestionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_value', models.FloatField()),
                ('activity_unit', models.CharField(max_length=20)),
                ('normalized_value', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=20)),
                ('emission_factor', models.FloatField()),
                ('co2e', models.FloatField()),
                ('confidence_score', models.FloatField(default=1.0)),
                ('anomaly_notes', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='esg.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalNormalizedEmissionRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_value', models.FloatField()),
                ('activity_unit', models.CharField(max_length=20)),
                ('normalized_value', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=20)),
                ('emission_factor', models.FloatField()),
                ('co2e', models.FloatField()),
                ('confidence_score', models.FloatField(default=1.0)),
                ('anomaly_notes', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esg.rawrecord')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esg.tenant')),
            ],
            options={
                'verbose_name': 'historical normalized emission record',
                'verbose_name_plural': 'historical normalized emission records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.tenant')),
            ],
        ),
    ]
