# Generated by Django 5.0.3 on 2026-05-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esg.tenant'),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='source_system',
            field=models.CharField(choices=[('SAP', 'SAP ERP'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Travel System')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esg.tenant'),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='normalizedemissionrecord',
            name='raw_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esg.rawrecord'),
        ),
        migrations.AlterField(
            model_name='normalizedemissionrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esg.tenant'),
        ),
    ]
